# Generated by Django 5.0.7 on 2024-07-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['track_number']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
