# Generated by Django 5.0.7 on 2024-07-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.CharField(max_length=2),
        ),
    ]
