# Generated by Django 5.0.7 on 2024-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_playlist_albums_album_playlists_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='albums',
            field=models.ManyToManyField(related_name='playlists', to='main_app.album'),
        ),
    ]
