# Generated by Django 5.0.7 on 2024-08-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
    ]
